# Generated by Django 5.1.7 on 2026-03-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_trek_coordinates_lat_trek_coordinates_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trek',
            name='altitude_m',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trek',
            name='cost_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trek',
            name='cost_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trek',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='trek',
            name='route_geojson',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
