# Generated by Django 5.1.7 on 2026-03-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_numeric_and_geojson_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='trek',
            name='duration_days_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trek',
            name='duration_days_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
